<html>
<head>
<title>${item.name!"商品名称"}</title>
</head>
<body>
<p>${item.id!"商品ID"}</p>
<p>${item.name!"商品名称"}</p>
<p>${item.image!"商品名称"}</p>
<p>${item.description!"商品描述"}</p>
<p>${item.price!"商品价格"}</p>
<p>${item.linkedRole!"商品链接角色"}</p>
</body>
</html>